version: '2'

volumes:
  webroot:
  certificates:

services:

  api:
    image: todorus/openkaart-resources:production
    ports:
      - "5000"
    depends_on:
      - db
    links:
      - db:database

  db:
    image: neo4j:3.0.6
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
    volumes:
      - ./data:/data

  web:
    image: todorus/openkaart-resources:nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    links:
      - api:api
    volumes:
      - webroot:/var/www
      - certificates:/certificates
