version: '2'
services:

  api:
    build:
      context: ../../
      dockerfile: regions/.docker/api.Dockerfile
    image: openkaart-resources-regions:api
    ports:
      - "5000"
    depends_on:
      - db
    links:
      - db:database
    command: python start_server.py

  db:
    image: neo4j:3.0.6
    ports:
      - "7474"
      - "7687"
    environment:
      - NEO4J_AUTH=none

  nginx:
    build:
      context: nginx
      dockerfile: nginx.Dockerfile
    image: openkaart-resources-regions:nginx
    ports:
      - "80:80"
    depends_on:
      - api
    links:
      - api:regions-api

  test:
    build:
      context: ../../../
      dockerfile: app/regions/.docker/test.Dockerfile
    image: openkaart-resources-regions:test
    depends_on:
      - api
      - db
    links:
      - api:api
      - db:database
    command: bash -c "sleep 10s; echo 'starting tests'; nose2"
