version: '2'
services:

  api:
    build:
      context: ..
      dockerfile: deployment/api/Dockerfile
    image: todorus/openkaart-resources:production
    ports:
      - "5000"
    depends_on:
      - db
    links:
      - db:database

  db:
    image: neo4j:3.0.6
    ports:
      - "7474:7474"
      - "7687"
    environment:
      - NEO4J_AUTH=none

  web:
    image: todorus/openkaart-resources:nginx
    ports:
      - "80:80"
    depends_on:
      - api
    links:
      - api:api
