version: '2'
services:
  web:
    build:
      context: ../../
      dockerfile: ./.docker/production/Dockerfile
    image: openkaart-resources-regions:production
    ports:
      - "5000:5000"
    volumes:
      - ../../code:/app
